name: Convox Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: login
      uses: convox/action-login@v1
      with:
        password: ${{ secrets.CONVOX_DEPLOY_KEY }}
    - name: build
      id: build
      uses: convox/action-build@v1
      with:
        rack: cgdemo/do-test
        app: deno
    - name: promote
      uses: convox/action-promote@v1
      with:
        rack: cgdemo/do-test
        app: deno
        release: ${{ steps.build.outputs.release }}